name:                haskell-spiral-matrix
version:             0.1.0.0
github:              "hsh814/haskell-spiral-matrix"
license:             BSD3
author:              "hsh814"
maintainer:          "hsh814@naver.com"
copyright:           "2020 hsh814"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hsh814/haskell-spiral-matrix#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-spiral-matrix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-spiral-matrix

tests:
  haskell-spiral-matrix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-spiral-matrix
